server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: example-mongo
  data:
    mongodb:
      host: 192.168.2.242
      port: 27017
      database: ground
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 10
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
    time-zone: GMT+8
logging:
  config: classpath:config/logback.xml